blank_issues_enabled: false
contact_links:
  - name: Chipyard Mailing List
    url: https://groups.google.com/forum/#!forum/chipyard
    about: Please ask and answer questions here.
  - name: FireSim Mailing List
    url: https://groups.google.com/forum/#!forum/firesim
    about: Please ask and answer questions here.
  - name: Rocket Chip Support
    url: https://github.com/chipsalliance/rocket-chip/issues
    about: Please ask and answer questions here.
  - name: Chisel Support
    url: https://www.chisel-lang.org/community.html
    about: Please ask and answer questions here.
